import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import profilePic from '../img/IMG_4104.JPG'
import Link from 'next/link'
import Navbar from '../components/navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hi, I am JeongHyun Heo</h1>
        <div className={styles.space}>
          <Link href={"/about"}><Image src={profilePic} className={styles.img} height={300} width={300}/></Link>
        </div>
        <h2>
          If you want to know more about me, click the picture!
        </h2>
        <p className={styles.description}>
          or
        </p>
        <h2>
          click one of these cards:
        </h2>
        <div className={styles.grid}>
          <a className={styles.card}>
            <Link href="/about"><h2>About Me &rarr;</h2></Link>
          </a>
          <a className={styles.card}>
            <Link href="/interests"><h2>My<br/>interests<br/>&rarr;</h2></Link>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
